security:
  enable_authenticator_manager: true
  password_hashers:
    App\Entity\systemUser:
      id: App\Security\Hasher\MD5PasswordHasher
  providers:
    user_provider:
      id: App\Security\Core\SystemUser\SystemUserProvider
  firewalls:
    docs:
      pattern: ^/api/docs
      methods: [ GET ]
      security: false
    login:
      pattern: /api/systemUser/login
      stateless: true
      provider: user_provider
      json_login:
        check_path: /api/systemUser/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false
    api:
      pattern: ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
