App\Entity\systemAction:
  attributes:
    name:
      groups: [ systemAction_read, systemAction_create, systemAction_update ]
    description:
      groups: [ systemAction_read, systemAction_create, systemAction_update ]