App\Entity\TipoDeTicket:
  attributes:
    TipoTicket:
      groups: [ TipoDeTicket_read, TipoDeTicket_create, TipoDeTicket_update ]
    DiasLimiteResolucion:
      groups: [ TipoDeTicket_read, TipoDeTicket_create, TipoDeTicket_update ]