App\Entity\TipoDeClientePersona:
  attributes:
    Nombre:
      groups: [ TipoDeClientePersona_read, TipoDeClientePersona_create, TipoDeClientePersona_update ]
    Descripcion:
      groups: [ TipoDeClientePersona_read, TipoDeClientePersona_create, TipoDeClientePersona_update ]